### ISSUE TITLE
Some issues after Grav v1.1.x update

### ISSUE THREAD

**Issue by grumero** [getgrav/grav-skeleton-landio-site#6]
Hi there,

This sceleton is not working as is. Users are forced to upgrade to Grav v1.1.x.
Classes within markup are not working and show up on the rendered page.
Instead of:
`### Contact us {.text-center .m-b-lg} )`
I had to use pure HTML:
`<h3 class="text-center m-b-lg">Contact us</h3>`

For centering the contact-form also on medium format screens I added the class `col-md-offset-2` to the corresponding divs.

Issue with the navigation: 
rightmost entry reads as `LOGIN_PLUGIN.BTN_LOGIN`. Seems there is some issue with fetching the variable value.

I did not get the contact form to send emails. Crosschecking my mail settings with another sceleton (ceevee) worked like charm. Have no clue how to solve this.

This is a great template and I'd like to use this, but I'd need to have this contact form working.

Best regards.
Peter

**Comment by rhukster** [comment]
Did you download the package from the releases?

**Comment by grumero** [comment]
Hi. Yes I downloaded the skeleton from the releases here: https://getgrav.org/downloads/skeletons <https://getgrav.org/downloads/skeletons>
The download button provided this link:
https://github.com/getgrav/grav-skeleton-landio-site/releases/download/1.0.0/grav-skeleton-landio-site-v1.0.0.zip

**Comment by flaviocopes** [comment]
Ok so, the skeleton is [including Admin](https://github.com/getgrav/grav-skeleton-landio-site/blob/develop/.dependencies#L14-L17), but Admin 1.1 instead of the stable release. Should we drop including Admin? Must be the only skeleton doing this.

I tested the class on the h3. Works fine. You have a trailing `)` that makes it not work.

I fixed the Landio theme form issue on medium screens.

I cannot find the LOGIN_PLUGIN.BTN_LOGIN string, can you make a screenshot? Did you add some twig edit?

The form worked fine for me, I got the email. Please use a testing SMTP service to test emails, don't rely on PHP mail() (which is the default of the email plugin, but not always works due to various reasons). See https://github.com/getgrav/grav-plugin-email#testing-emails

**Comment by grumero** [comment]
OK, I see. Here is what I am experiencing:
Downloaded the skeleton and run it. As of the admin panel is newer than GRAV core I am get a message to upgrade to 1.1.x.  ![message](https://cloud.githubusercontent.com/assets/17725938/15616293/0b1b3df2-2443-11e6-920c-1c635d387f38.png)

But that's not working because setting 
```
gpm: 
   releases: testing
```
in the system.yaml is not working at this state. So I get:
`$ bin/gpm selfupgrade -f
You are already running the latest version of Grav (v1.0.10) released on Thu Feb 11 22:37:50 2016`
But in this state I can not get the admin panel running or create an user account.

To make it work with Grav 1.1.x I loadet the 1.1.5beta core + admin and copied the user folder from the skeleton in there. This was the only way I knew to get away from Grav 1.0.10

But than the classes within the markup do not render correct, as described before (my trayling  `)` was only a mistake in my first post as I copied this from the outcommented markup)
![classes](https://cloud.githubusercontent.com/assets/17725938/15616368/9624dc82-2443-11e6-9094-2926343e8984.png)
![classes2](https://cloud.githubusercontent.com/assets/17725938/15616410/dbf45bac-2443-11e6-8dab-b3483abdf7f1.png)

The email function is also broken than and the thankyou page will not show up.

**Today I did this**: stayed at the Grav v1.0.10 and installed the older admin-panel to get it up and running with the given core. This way the email function is working fine ( I only ever use SMTP ) and the classes within markup rendered also fine. 

But still there is this `LOGIN_PLUGIN.BTN_LOGIN` thing and I don't find where this value will be set.
![login button](https://cloud.githubusercontent.com/assets/17725938/15616547/dc94247e-2444-11e6-8d01-65a38975c026.png)
This shows up also for the login button.
![login2](https://cloud.githubusercontent.com/assets/17725938/15616707/cef0496e-2445-11e6-9a3b-f29307bf34bc.png)

Anyway, now I know how I can use your template with v.1.0.10 and that's fine as I don't need the user login right now.
Maybe you could do the skeleton download yourself and try to get it up and running like a noob like me. 

Hope I could bring some light into this and thanks for the quick reply.

**Comment by flaviocopes** [comment]
I did try this with the skeleton download, 

Admin should not be included in the first place, that caused the other problems. @rhukster we should remove this, and recompile the skeleton? As it's getting Admin 1.1. Also now can include the landio theme update.

I can get the "Contact us" working. Make sure you enabled Markdown Extra in the config.

I fixed the language strings in the theme repository: https://github.com/getgrav/grav-theme-landio/commits/develop they were inverted.

**Comment by Staxed** [comment]
Am I missing something with why this issue was closed?  I am testing out grav for the first time and wanted to give this skeleton a try, but I am still experiencing the exact same problem this issue was started about.  Downloading this from the website or the releases here on Github creates the same problem either way, the admin plugin is the wrong version and it wants you to upgrade the core.

**Comment by grumero** [comment]
You can get around this by installing the older admin plugin (uninstalling the version that came with the skeleton first)
Also a view other issues are fixed in the development version of the theme, so you better get the stand alone theme and not the skeleton.
Just my two cents.

**Comment by flaviocopes** [comment]
Just removed `admin` from .dependencies
